### ISSUE TITLE
Running in Mac

### ISSUE THREAD

**Issue by gracoes** [countincognito/Zametek.ProjectPlan#45]
Hey,

I'm trying to run the app on MacOs Monterey (v12.6.5) and I'm having trouble making it work.
I've tried
- Cloning the repo and running `make run`
The project is built successfully but fails when trying to run it with the error
```
Unhandled exception: System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/Zametek.ProjectPlan/src/Zametek.ProjectPlan/bin/Debug/net6.0/win-x64/Zametek.ProjectPlan.exe' with working directory '/Zametek.ProjectPlan'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

- Running the `ProjectPlan.exe` but I couldn't figure a way to to do it.

Can you give me any tip please?

Thanks and awesome work.

PS
My `dotnet` version is 6.0.401

**Comment by countincognito** [comment]
It looks like Make is trying to run a Windows executable. I have updated the makefile in the develop branch to have OS-specific targets. In your case, try `make run-mac`.

Unfortunately, I don't have access to a Mac to test this. However, I have tried it on a Linux box and it seems to work in that instance. If you can please let me know if it works for you, then I can move it to the master branch.

Thanks

**Comment by gracoes** [comment]
Yep, it worked 👍 
Thanks for the quick reply
